project_name: mc-router
release:
  github:
    owner: itzg
    name: mc-router
before:
  hooks:
    - go mod download
brews:
  - install: |
      bin.install "mc-router"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  main: ./cmd/mc-router
  binary: mc-router
  env:
    - CGO_ENABLED=0
archives:
  - id: tar_gz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
    - LICENSE*
    - README*
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
dockers:
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "itzg/{{ .ProjectName }}:latest"
    goos: linux
    goarch: amd64
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
    goos: linux
    goarch: arm64
docker_manifests:
  - name_template: "itzg/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'
