project_name: mc-router
release:
  github:
    owner: itzg
    name: mc-router
before:
  hooks:
    - go mod download
brew:
  install: bin.install "mc-router"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  main: ./cmd/mc-router
  binary: mc-router
  env:
    - CGO_ENABLED=0
archives:
  - id: tar_gz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
dockers:
  - image_templates:
      - "itzg/mc-router:latest"
      - "itzg/mc-router:{{.Tag}}"
    goos: linux
    goarch: amd64
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'