project_name: mc-router
release:
  github:
    owner: itzg
    name: mc-router
before:
  hooks:
    - go mod download
brews:
  - install: |
      bin.install "mc-router"
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/mc-router
    binary: mc-router
    env:
      - CGO_ENABLED=0
archives:
  - id: tar_gz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
dockers:
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
    goarch: amd64
    build_flag_templates:
      - --platform
      - linux/amd64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
    goarch: arm64
    build_flag_templates:
      - --platform
      - linux/arm64
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - --platform
      - linux/arm/v6
      - --load
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - name_template: "itzg/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
  - name_template: "itzg/{{ .ProjectName }}:latest"
    image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'
