# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

defaults: &defaults
  docker:
    # specify the version
    - image: circleci/golang:1.10

  working_directory: /go/src/github.com/itzg/mc-router


jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "glide.lock" }}
            - cache-{{ arch }}-{{ .Branch }}
            - cache

      - run:
          name: install glide
          command: curl https://glide.sh/get | sh
      - run:
          name: install dependencies
          command: glide install

      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
            - vendor

      - run: make test

  release:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: install glide
          command: curl https://glide.sh/get | sh
      - run:
          name: install dependencies
          command: glide install

      - setup_remote_docker
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run: make release

workflows:
  version: 2
  incremental:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^\d+\.\d+\.\d+/
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/